// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIZ67w8YxbOGQA6XSI7_eCnHq6-jBodQ',
    appId: '1:16032161551:web:7b39b770cb036bd581287a',
    messagingSenderId: '16032161551',
    projectId: 'agrilink-app-c137b',
    authDomain: 'agrilink-app-c137b.firebaseapp.com',
    databaseURL: 'https://agrilink-app-c137b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrilink-app-c137b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVfc7RJnAlEY2XsEOppfXgr-fshkp0s4',
    appId: '1:16032161551:android:845970be65907a8a81287a',
    messagingSenderId: '16032161551',
    projectId: 'agrilink-app-c137b',
    databaseURL: 'https://agrilink-app-c137b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrilink-app-c137b.firebasestorage.app',
  );
}
